version: '3.1'

services:

  db:
    #build: ./db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  adminer:
    #build: ./adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080